loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi
gateway:
  enabled: false
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
