#!/usr/bin/env bash
# Quick check for Render services that can be automated

echo "=== Render Services Quick Check ==="
echo ""
echo "Since I can't access your Render dashboard directly, here's what you can do:"
echo ""
echo "1. Open: https://dashboard.render.com"
echo "2. Go to Services tab"
echo "3. For each service, use this quick checklist:"
echo ""
echo "   [ ] Service name: _______________"
echo "   [ ] Last deployed: More than 3 months ago? → Likely DELETE"
echo "   [ ] Status: Running? → Check if needed"
echo "   [ ] Status: Suspended/Stopped? → Likely DELETE or SUSPEND"
echo "   [ ] Has NeoLight in name? → Likely KEEP or SUSPEND"
echo "   [ ] Unknown service? → Likely DELETE"
echo ""
echo "Quick Actions:"
echo "  - Old test deployments (>3 months) → DELETE"
echo "  - Unknown services → DELETE"
echo "  - NeoLight services (not active) → SUSPEND"
echo "  - NeoLight services (active) → KEEP"
echo ""
