name: Build & Deploy (K8s Canary)
on:
  push:
    branches: [ "main" ]
    paths: ["**/*.py","Dockerfile","requirements.txt","static/**","k8s/**",".github/workflows/**"]
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build images
      run: |
        IMAGE=ghcr.io/${{ github.repository_owner }}/aimoneyweb
        docker build -t $IMAGE:stable .
        docker tag $IMAGE:stable $IMAGE:canary
        docker push $IMAGE:stable
        docker push $IMAGE:canary
    - name: Upload k8s manifests (artifact)
      uses: actions/upload-artifact@v4
      with:
        name: k8s-manifests
        path: k8s/
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: k8s-manifests
        path: k8s
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.0'
    - name: Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${KUBECONFIG_CONTENT}" > ~/.kube/config
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
    - name: Apply manifests
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/configmap.yaml
        kubectl apply -f k8s/deploy-stable.yaml
        kubectl apply -f k8s/deploy-canary.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
